name: Deploy Site
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Print list of dist files
        run: |
          cd dist
          ls
