name: Run Tests in Docker
on: workflow_dispatch
env:
  # Setting an environment variable with the value of a configuration variable
  TEST: ${{ vars.TEST }}
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #   - name: Install dependencies
      #     run: npm install
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build Docker Image
        run: docker build -t sandbox:latest .
      - name: Run tests
        run: docker run -d --name sandbox-app sandbox:latest
      - name: Print logs
        run: docker logs sandbox-app
