name: Deploy Site
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: List Github Info
        run: |
          echo "${{toJSON(github)}}"
          echo "test"
